enum DriverCapability {
  joins,
  insertUsing,
  queryDeletes,
  schemaIntrospection,
  returning,
  transactions,
  threadCount,
  adHocQueryUpdates,
  advancedQueryBuilders,
  sqlPreviews,
  increment,
  rawSQL,
  relationAggregates,
}
