builders:
  ormed:
    import: 'package:ormed/builder.dart'
    builder_factories: ['ormModelBuilder']
    build_extensions: {'.dart': ['.orm.dart', '.orm_model.json']}
    auto_apply: dependents
    build_to: source
    applies_builders: ['source_gen|combining_builder']
    runs_before:
      - ormed|orm_registry
  orm_registry:
    import: 'package:ormed/src/builder/orm_registry_builder.dart'
    builder_factories: ['ormRegistryBuilder']
    build_extensions: {'pubspec.yaml': ['lib/orm_registry.g.dart']}
    auto_apply: dependents
    build_to: source
    required_inputs: ['lib/**/*.orm_model.json']
targets:
  $default:
    sources:
      - lib/**
      - example/**
      - test/**
      - $package$
    builders:
      ormed|ormed:
        enabled: true
